#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AKM

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass AKM.AKM_C
// 0x01E0 (0x0530 - 0x0350)
class UAKM_C final : public UAnimInstance
{
public:
	uint8                                         Pad_348[0x8];                                      // 0x0348(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0350(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x0358(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x0360(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0368(0x0020)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x0388(0x0048)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone;                          // 0x03D0(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x04F8(0x0020)()
	class AWEP_C*                                 As_WEP;                                            // 0x0518(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        SliderBack;                                        // 0x0520(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void ExecuteUbergraph_AKM(int32 EntryPoint);
	void Init_Wep(class AWEP_C* WEP);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AKM_C">();
	}
	static class UAKM_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAKM_C>();
	}
};
static_assert(alignof(UAKM_C) == 0x000010, "Wrong alignment on UAKM_C");
static_assert(sizeof(UAKM_C) == 0x000530, "Wrong size on UAKM_C");
static_assert(offsetof(UAKM_C, UberGraphFrame) == 0x000350, "Member 'UAKM_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UAKM_C, AnimBlueprintExtension_PropertyAccess) == 0x000358, "Member 'UAKM_C::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UAKM_C, AnimBlueprintExtension_Base) == 0x000360, "Member 'UAKM_C::AnimBlueprintExtension_Base' has a wrong offset!");
static_assert(offsetof(UAKM_C, AnimGraphNode_Root) == 0x000368, "Member 'UAKM_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UAKM_C, AnimGraphNode_Slot) == 0x000388, "Member 'UAKM_C::AnimGraphNode_Slot' has a wrong offset!");
static_assert(offsetof(UAKM_C, AnimGraphNode_ModifyBone) == 0x0003D0, "Member 'UAKM_C::AnimGraphNode_ModifyBone' has a wrong offset!");
static_assert(offsetof(UAKM_C, AnimGraphNode_ComponentToLocalSpace) == 0x0004F8, "Member 'UAKM_C::AnimGraphNode_ComponentToLocalSpace' has a wrong offset!");
static_assert(offsetof(UAKM_C, As_WEP) == 0x000518, "Member 'UAKM_C::As_WEP' has a wrong offset!");
static_assert(offsetof(UAKM_C, SliderBack) == 0x000520, "Member 'UAKM_C::SliderBack' has a wrong offset!");

}

