#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_HorrorMob

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "AnimBP_HorrorMob_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass AnimBP_HorrorMob.AnimBP_HorrorMob_C
// 0x0220 (0x0570 - 0x0350)
class UAnimBP_HorrorMob_C final : public UAnimInstance
{
public:
	uint8                                         Pad_348[0x8];                                      // 0x0348(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0350(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct AnimBP_HorrorMob::FAnimBlueprintGeneratedMutableData __AnimBlueprintMutables;                           // 0x0358(0x0008)(HasGetValueTypeHash)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x0360(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x0368(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0370(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone;                          // 0x0390(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x04B8(0x0020)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x04D8(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x04F8(0x0048)()
	class ACharacter*                             Near_Player;                                       // 0x0540(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class AHorrorMob_C*                           As_Horror_Mob;                                     // 0x0548(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               HeadRotation;                                      // 0x0550(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	float                                         Play_Rate;                                         // 0x0568(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void BlueprintBeginPlay();
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_HorrorMob_AnimGraphNode_ModifyBone_0220CA614FC18EFB0DBCCE98CBE5662B();
	void ExecuteUbergraph_AnimBP_HorrorMob(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AnimBP_HorrorMob_C">();
	}
	static class UAnimBP_HorrorMob_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAnimBP_HorrorMob_C>();
	}
};
static_assert(alignof(UAnimBP_HorrorMob_C) == 0x000010, "Wrong alignment on UAnimBP_HorrorMob_C");
static_assert(sizeof(UAnimBP_HorrorMob_C) == 0x000570, "Wrong size on UAnimBP_HorrorMob_C");
static_assert(offsetof(UAnimBP_HorrorMob_C, UberGraphFrame) == 0x000350, "Member 'UAnimBP_HorrorMob_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UAnimBP_HorrorMob_C, __AnimBlueprintMutables) == 0x000358, "Member 'UAnimBP_HorrorMob_C::__AnimBlueprintMutables' has a wrong offset!");
static_assert(offsetof(UAnimBP_HorrorMob_C, AnimBlueprintExtension_PropertyAccess) == 0x000360, "Member 'UAnimBP_HorrorMob_C::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UAnimBP_HorrorMob_C, AnimBlueprintExtension_Base) == 0x000368, "Member 'UAnimBP_HorrorMob_C::AnimBlueprintExtension_Base' has a wrong offset!");
static_assert(offsetof(UAnimBP_HorrorMob_C, AnimGraphNode_Root) == 0x000370, "Member 'UAnimBP_HorrorMob_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UAnimBP_HorrorMob_C, AnimGraphNode_ModifyBone) == 0x000390, "Member 'UAnimBP_HorrorMob_C::AnimGraphNode_ModifyBone' has a wrong offset!");
static_assert(offsetof(UAnimBP_HorrorMob_C, AnimGraphNode_ComponentToLocalSpace) == 0x0004B8, "Member 'UAnimBP_HorrorMob_C::AnimGraphNode_ComponentToLocalSpace' has a wrong offset!");
static_assert(offsetof(UAnimBP_HorrorMob_C, AnimGraphNode_LocalToComponentSpace) == 0x0004D8, "Member 'UAnimBP_HorrorMob_C::AnimGraphNode_LocalToComponentSpace' has a wrong offset!");
static_assert(offsetof(UAnimBP_HorrorMob_C, AnimGraphNode_SequencePlayer) == 0x0004F8, "Member 'UAnimBP_HorrorMob_C::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(UAnimBP_HorrorMob_C, Near_Player) == 0x000540, "Member 'UAnimBP_HorrorMob_C::Near_Player' has a wrong offset!");
static_assert(offsetof(UAnimBP_HorrorMob_C, As_Horror_Mob) == 0x000548, "Member 'UAnimBP_HorrorMob_C::As_Horror_Mob' has a wrong offset!");
static_assert(offsetof(UAnimBP_HorrorMob_C, HeadRotation) == 0x000550, "Member 'UAnimBP_HorrorMob_C::HeadRotation' has a wrong offset!");
static_assert(offsetof(UAnimBP_HorrorMob_C, Play_Rate) == 0x000568, "Member 'UAnimBP_HorrorMob_C::Play_Rate' has a wrong offset!");

}

