#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_Emote

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_Emote.E_Emote
// NumValues: 0x0003
enum class E_Emote : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	E_MAX                                    = 2,
};

}

