#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EFontPalette

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EFontPalette.EFontPalette
// NumValues: 0x000B
enum class EFontPalette : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator3                           = 2,
	NewEnumerator10                          = 3,
	NewEnumerator4                           = 4,
	NewEnumerator5                           = 5,
	NewEnumerator6                           = 6,
	NewEnumerator7                           = 7,
	NewEnumerator8                           = 8,
	NewEnumerator9                           = 9,
	EFontPalette_MAX                         = 10,
};

}

