#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FKeyBinderButtonData

#include "Basic.hpp"

#include "EInputDeviceType_structs.hpp"


namespace SDK
{

// UserDefinedStruct FKeyBinderButtonData.FKeyBinderButtonData
// 0x0020 (0x0020 - 0x0000)
struct FFKeyBinderButtonData final
{
public:
	class FName                                   PlayerMappableOptionsName_12_6AA835D54DCEE96811E5D0996332A529; // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EInputDeviceType                              AllowedInputDeviceType_15_DAFF5D1940A78F8E6E1147A2B8E5AFDE; // 0x0008(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UInputMappingContext*                   InputMappingContext_21_1F3BE39F474046CD0DF5DF950CD672DB; // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UInputAction*                           InputAction_22_530579024C59D26661E9C0881054F689;   // 0x0018(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FFKeyBinderButtonData) == 0x000008, "Wrong alignment on FFKeyBinderButtonData");
static_assert(sizeof(FFKeyBinderButtonData) == 0x000020, "Wrong size on FFKeyBinderButtonData");
static_assert(offsetof(FFKeyBinderButtonData, PlayerMappableOptionsName_12_6AA835D54DCEE96811E5D0996332A529) == 0x000000, "Member 'FFKeyBinderButtonData::PlayerMappableOptionsName_12_6AA835D54DCEE96811E5D0996332A529' has a wrong offset!");
static_assert(offsetof(FFKeyBinderButtonData, AllowedInputDeviceType_15_DAFF5D1940A78F8E6E1147A2B8E5AFDE) == 0x000008, "Member 'FFKeyBinderButtonData::AllowedInputDeviceType_15_DAFF5D1940A78F8E6E1147A2B8E5AFDE' has a wrong offset!");
static_assert(offsetof(FFKeyBinderButtonData, InputMappingContext_21_1F3BE39F474046CD0DF5DF950CD672DB) == 0x000010, "Member 'FFKeyBinderButtonData::InputMappingContext_21_1F3BE39F474046CD0DF5DF950CD672DB' has a wrong offset!");
static_assert(offsetof(FFKeyBinderButtonData, InputAction_22_530579024C59D26661E9C0881054F689) == 0x000018, "Member 'FFKeyBinderButtonData::InputAction_22_530579024C59D26661E9C0881054F689' has a wrong offset!");

}

