#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: M4a1

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function M4a1.M4a1_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct M4a1_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(M4a1_C_AnimGraph) == 0x000008, "Wrong alignment on M4a1_C_AnimGraph");
static_assert(sizeof(M4a1_C_AnimGraph) == 0x000010, "Wrong size on M4a1_C_AnimGraph");
static_assert(offsetof(M4a1_C_AnimGraph, AnimGraph_0) == 0x000000, "Member 'M4a1_C_AnimGraph::AnimGraph_0' has a wrong offset!");

// Function M4a1.M4a1_C.ExecuteUbergraph_M4a1
// 0x0010 (0x0010 - 0x0000)
struct M4a1_C_ExecuteUbergraph_M4a1 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AWEP_C*                                 K2Node_Event_Wep;                                  // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(M4a1_C_ExecuteUbergraph_M4a1) == 0x000008, "Wrong alignment on M4a1_C_ExecuteUbergraph_M4a1");
static_assert(sizeof(M4a1_C_ExecuteUbergraph_M4a1) == 0x000010, "Wrong size on M4a1_C_ExecuteUbergraph_M4a1");
static_assert(offsetof(M4a1_C_ExecuteUbergraph_M4a1, EntryPoint) == 0x000000, "Member 'M4a1_C_ExecuteUbergraph_M4a1::EntryPoint' has a wrong offset!");
static_assert(offsetof(M4a1_C_ExecuteUbergraph_M4a1, K2Node_Event_Wep) == 0x000008, "Member 'M4a1_C_ExecuteUbergraph_M4a1::K2Node_Event_Wep' has a wrong offset!");

// Function M4a1.M4a1_C.Init Wep
// 0x0008 (0x0008 - 0x0000)
struct M4a1_C_Init_Wep final
{
public:
	class AWEP_C*                                 WEP;                                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(M4a1_C_Init_Wep) == 0x000008, "Wrong alignment on M4a1_C_Init_Wep");
static_assert(sizeof(M4a1_C_Init_Wep) == 0x000008, "Wrong size on M4a1_C_Init_Wep");
static_assert(offsetof(M4a1_C_Init_Wep, WEP) == 0x000000, "Member 'M4a1_C_Init_Wep::WEP' has a wrong offset!");

}

