#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PC_Zombie

#include "Basic.hpp"

#include "PC_Zombie_classes.hpp"
#include "PC_Zombie_parameters.hpp"


namespace SDK
{

// Function PC_Zombie.PC_Zombie_C.BreakTimer
// (Public, BlueprintCallable, BlueprintEvent)

void APC_Zombie_C::BreakTimer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "BreakTimer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PC_Zombie.PC_Zombie_C.CanCreateKickVote
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    CanCreateKickVote_                                     (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::CanCreateKickVote(bool* CanCreateKickVote_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "CanCreateKickVote");

	Params::PC_Zombie_C_CanCreateKickVote Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (CanCreateKickVote_ != nullptr)
		*CanCreateKickVote_ = Parms.CanCreateKickVote_;
}


// Function PC_Zombie.PC_Zombie_C.CanKickThisPlayer?
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           PlayerID                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// bool                                    True_                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::CanKickThisPlayer_(const class FString& PlayerID, bool* True_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "CanKickThisPlayer?");

	Params::PC_Zombie_C_CanKickThisPlayer_ Parms{};

	Parms.PlayerID = std::move(PlayerID);

	UObject::ProcessEvent(Func, &Parms);

	if (True_ != nullptr)
		*True_ = Parms.True_;
}


// Function PC_Zombie.PC_Zombie_C.ClearMap
// (Public, BlueprintCallable, BlueprintEvent)

void APC_Zombie_C::ClearMap()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "ClearMap");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PC_Zombie.PC_Zombie_C.ConnectionInfos
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FLinearColor                     Color                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::ConnectionInfos(const struct FLinearColor& Color)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "ConnectionInfos");

	Params::PC_Zombie_C_ConnectionInfos Parms{};

	Parms.Color = std::move(Color);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.ElectricalAction
// (Public, BlueprintCallable, BlueprintEvent)

void APC_Zombie_C::ElectricalAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "ElectricalAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PC_Zombie.PC_Zombie_C.EndWave
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Wave_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EN_WaveClass                            EN_WaveClass                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::EndWave(int32 Wave_0, EN_WaveClass EN_WaveClass)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "EndWave");

	Params::PC_Zombie_C_EndWave Parms{};

	Parms.Wave_0 = Wave_0;
	Parms.EN_WaveClass = EN_WaveClass;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.Event Begin Play Chat
// (BlueprintCallable, BlueprintEvent)

void APC_Zombie_C::Event_Begin_Play_Chat()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "Event Begin Play Chat");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PC_Zombie.PC_Zombie_C.Event Ragdoll End
// (Public, BlueprintCallable, BlueprintEvent)

void APC_Zombie_C::Event_Ragdoll_End()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "Event Ragdoll End");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PC_Zombie.PC_Zombie_C.EventRagdollStart
// (Public, BlueprintCallable, BlueprintEvent)

void APC_Zombie_C::EventRagdollStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "EventRagdollStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PC_Zombie.PC_Zombie_C.ExecuteUbergraph_PC_Zombie
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::ExecuteUbergraph_PC_Zombie(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "ExecuteUbergraph_PC_Zombie");

	Params::PC_Zombie_C_ExecuteUbergraph_PC_Zombie Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.FindBestSpawn
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           InputPin                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// struct FTransform                       FarestTransform_return                                 (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::FindBestSpawn(const class FString& InputPin, struct FTransform* FarestTransform_return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "FindBestSpawn");

	Params::PC_Zombie_C_FindBestSpawn Parms{};

	Parms.InputPin = std::move(InputPin);

	UObject::ProcessEvent(Func, &Parms);

	if (FarestTransform_return != nullptr)
		*FarestTransform_return = std::move(Parms.FarestTransform_return);
}


// Function PC_Zombie.PC_Zombie_C.FocusControlOnGame
// (Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent)

void APC_Zombie_C::FocusControlOnGame()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "FocusControlOnGame");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PC_Zombie.PC_Zombie_C.Get BP Menu Controller Component
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBP_MenuControllerComponent_C*    BP_Menu_Controller_Component                           (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::Get_BP_Menu_Controller_Component(class UBP_MenuControllerComponent_C** BP_Menu_Controller_Component)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "Get BP Menu Controller Component");

	Params::PC_Zombie_C_Get_BP_Menu_Controller_Component Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (BP_Menu_Controller_Component != nullptr)
		*BP_Menu_Controller_Component = Parms.BP_Menu_Controller_Component;
}


// Function PC_Zombie.PC_Zombie_C.Get Stamina
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Stamina                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::Get_Stamina(double* Stamina)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "Get Stamina");

	Params::PC_Zombie_C_Get_Stamina Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Stamina != nullptr)
		*Stamina = Parms.Stamina;
}


// Function PC_Zombie.PC_Zombie_C.GetBlured
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Blured                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::GetBlured(double* Blured)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "GetBlured");

	Params::PC_Zombie_C_GetBlured Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Blured != nullptr)
		*Blured = Parms.Blured;
}


// Function PC_Zombie.PC_Zombie_C.GetBurnedRef
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USceneComponent*                  BurnedMesh                                             (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::GetBurnedRef(class USceneComponent** BurnedMesh)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "GetBurnedRef");

	Params::PC_Zombie_C_GetBurnedRef Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (BurnedMesh != nullptr)
		*BurnedMesh = Parms.BurnedMesh;
}


// Function PC_Zombie.PC_Zombie_C.GetCurrentRank
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   RankScore                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Rank_                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             CurrentRank                                            (Parm, OutParm)

void APC_Zombie_C::GetCurrentRank(int32* RankScore, int32* Rank_, class FText* CurrentRank)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "GetCurrentRank");

	Params::PC_Zombie_C_GetCurrentRank Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (RankScore != nullptr)
		*RankScore = Parms.RankScore;

	if (Rank_ != nullptr)
		*Rank_ = Parms.Rank_;

	if (CurrentRank != nullptr)
		*CurrentRank = std::move(Parms.CurrentRank);
}


// Function PC_Zombie.PC_Zombie_C.GetFlashBangEffect
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  FlashEffect                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::GetFlashBangEffect(double* FlashEffect)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "GetFlashBangEffect");

	Params::PC_Zombie_C_GetFlashBangEffect Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FlashEffect != nullptr)
		*FlashEffect = Parms.FlashEffect;
}


// Function PC_Zombie.PC_Zombie_C.GetGameMode
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FSTR_GamemodeWinInfo             GameMode                                               (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::GetGameMode(struct FSTR_GamemodeWinInfo* GameMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "GetGameMode");

	Params::PC_Zombie_C_GetGameMode Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (GameMode != nullptr)
		*GameMode = std::move(Parms.GameMode);
}


// Function PC_Zombie.PC_Zombie_C.GetHealth
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Health                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::GetHealth(double* Health)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "GetHealth");

	Params::PC_Zombie_C_GetHealth Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Health != nullptr)
		*Health = Parms.Health;
}


// Function PC_Zombie.PC_Zombie_C.GetKickedPlayerVoted
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class FString>                   KickplayerAlreadyVote                                  (Parm, OutParm)

void APC_Zombie_C::GetKickedPlayerVoted(TArray<class FString>* KickplayerAlreadyVote)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "GetKickedPlayerVoted");

	Params::PC_Zombie_C_GetKickedPlayerVoted Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (KickplayerAlreadyVote != nullptr)
		*KickplayerAlreadyVote = std::move(Parms.KickplayerAlreadyVote);
}


// Function PC_Zombie.PC_Zombie_C.GetMenuSettings
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBP_MenuControllerComponent_C*    Bp_MenuController                                      (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::GetMenuSettings(class UBP_MenuControllerComponent_C** Bp_MenuController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "GetMenuSettings");

	Params::PC_Zombie_C_GetMenuSettings Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Bp_MenuController != nullptr)
		*Bp_MenuController = Parms.Bp_MenuController;
}


// Function PC_Zombie.PC_Zombie_C.GetMutePlayer
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class FString>                   MutePlayer                                             (Parm, OutParm)

void APC_Zombie_C::GetMutePlayer(TArray<class FString>* MutePlayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "GetMutePlayer");

	Params::PC_Zombie_C_GetMutePlayer Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (MutePlayer != nullptr)
		*MutePlayer = std::move(Parms.MutePlayer);
}


// Function PC_Zombie.PC_Zombie_C.GetNewRank
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Name_0                                                 (Parm, OutParm)
// class UTexture2D*                       Image                                                  (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32                                   RankScore                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   RankPosition                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   RankDivision                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  PreviousRankProgress                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  RankProgress                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    NewRank_                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FSlateColor                      Color                                                  (Parm, OutParm)
// int32                                   Rank_Integer                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::GetNewRank(class FText* Name_0, class UTexture2D** Image, int32* RankScore, int32* RankPosition, int32* RankDivision, double* PreviousRankProgress, double* RankProgress, bool* NewRank_, struct FSlateColor* Color, int32* Rank_Integer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "GetNewRank");

	Params::PC_Zombie_C_GetNewRank Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Name_0 != nullptr)
		*Name_0 = std::move(Parms.Name_0);

	if (Image != nullptr)
		*Image = Parms.Image;

	if (RankScore != nullptr)
		*RankScore = Parms.RankScore;

	if (RankPosition != nullptr)
		*RankPosition = Parms.RankPosition;

	if (RankDivision != nullptr)
		*RankDivision = Parms.RankDivision;

	if (PreviousRankProgress != nullptr)
		*PreviousRankProgress = Parms.PreviousRankProgress;

	if (RankProgress != nullptr)
		*RankProgress = Parms.RankProgress;

	if (NewRank_ != nullptr)
		*NewRank_ = Parms.NewRank_;

	if (Color != nullptr)
		*Color = std::move(Parms.Color);

	if (Rank_Integer != nullptr)
		*Rank_Integer = Parms.Rank_Integer;
}


// Function PC_Zombie.PC_Zombie_C.GetPlayerConnected
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FSTR_PCInfo>              PlayerConnected                                        (Parm, OutParm)

void APC_Zombie_C::GetPlayerConnected(TArray<struct FSTR_PCInfo>* PlayerConnected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "GetPlayerConnected");

	Params::PC_Zombie_C_GetPlayerConnected Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (PlayerConnected != nullptr)
		*PlayerConnected = std::move(Parms.PlayerConnected);
}


// Function PC_Zombie.PC_Zombie_C.GetPlayerKickVote
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FSTR_KickVote>            KickVotePlayer                                         (Parm, OutParm)

void APC_Zombie_C::GetPlayerKickVote(TArray<struct FSTR_KickVote>* KickVotePlayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "GetPlayerKickVote");

	Params::PC_Zombie_C_GetPlayerKickVote Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (KickVotePlayer != nullptr)
		*KickVotePlayer = std::move(Parms.KickVotePlayer);
}


// Function PC_Zombie.PC_Zombie_C.GetPlayerSkin
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FSTR_TEST                        Player_Skin                                            (Parm, OutParm, HasGetValueTypeHash)
// bool                                    Valid_                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::GetPlayerSkin(struct FSTR_TEST* Player_Skin, bool* Valid_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "GetPlayerSkin");

	Params::PC_Zombie_C_GetPlayerSkin Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Player_Skin != nullptr)
		*Player_Skin = std::move(Parms.Player_Skin);

	if (Valid_ != nullptr)
		*Valid_ = Parms.Valid_;
}


// Function PC_Zombie.PC_Zombie_C.GetRagdollSystem
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWW_RagdollSystem_C*              Ragdoll_System                                         (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::GetRagdollSystem(class UWW_RagdollSystem_C** Ragdoll_System)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "GetRagdollSystem");

	Params::PC_Zombie_C_GetRagdollSystem Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Ragdoll_System != nullptr)
		*Ragdoll_System = Parms.Ragdoll_System;
}


// Function PC_Zombie.PC_Zombie_C.GetReady?
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsReady_                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::GetReady_(bool* IsReady_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "GetReady?");

	Params::PC_Zombie_C_GetReady_ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsReady_ != nullptr)
		*IsReady_ = Parms.IsReady_;
}


// Function PC_Zombie.PC_Zombie_C.GetServerSteamID
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           SteamID                                                (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void APC_Zombie_C::GetServerSteamID(class FString* SteamID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "GetServerSteamID");

	Params::PC_Zombie_C_GetServerSteamID Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SteamID != nullptr)
		*SteamID = std::move(Parms.SteamID);
}


// Function PC_Zombie.PC_Zombie_C.GetStarterWeapons
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FSTR_Actor>               Weapons                                                (Parm, OutParm)

void APC_Zombie_C::GetStarterWeapons(TArray<struct FSTR_Actor>* Weapons)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "GetStarterWeapons");

	Params::PC_Zombie_C_GetStarterWeapons Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Weapons != nullptr)
		*Weapons = std::move(Parms.Weapons);
}


// Function PC_Zombie.PC_Zombie_C.GetSteamID
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           SteamID                                                (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void APC_Zombie_C::GetSteamID(class FString* SteamID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "GetSteamID");

	Params::PC_Zombie_C_GetSteamID Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SteamID != nullptr)
		*SteamID = std::move(Parms.SteamID);
}


// Function PC_Zombie.PC_Zombie_C.GetSurvivorStatuts
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWW_SurvivorStatus_C*             SurvivorComponant                                      (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::GetSurvivorStatuts(class UWW_SurvivorStatus_C** SurvivorComponant)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "GetSurvivorStatuts");

	Params::PC_Zombie_C_GetSurvivorStatuts Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SurvivorComponant != nullptr)
		*SurvivorComponant = Parms.SurvivorComponant;
}


// Function PC_Zombie.PC_Zombie_C.GetTeam
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// E_Team                                  Team_0                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::GetTeam(E_Team* Team_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "GetTeam");

	Params::PC_Zombie_C_GetTeam Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Team_0 != nullptr)
		*Team_0 = Parms.Team_0;
}


// Function PC_Zombie.PC_Zombie_C.GetTeamList
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// E_Team                                  Team_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<struct FSTR_PCInfo>              Info                                                   (Parm, OutParm)

void APC_Zombie_C::GetTeamList(E_Team Team_0, TArray<struct FSTR_PCInfo>* Info)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "GetTeamList");

	Params::PC_Zombie_C_GetTeamList Parms{};

	Parms.Team_0 = Team_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Info != nullptr)
		*Info = std::move(Parms.Info);
}


// Function PC_Zombie.PC_Zombie_C.GetTopScore
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FSTR_PCInfo>              TopScore                                               (Parm, OutParm)

void APC_Zombie_C::GetTopScore(TArray<struct FSTR_PCInfo>* TopScore)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "GetTopScore");

	Params::PC_Zombie_C_GetTopScore Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (TopScore != nullptr)
		*TopScore = std::move(Parms.TopScore);
}


// Function PC_Zombie.PC_Zombie_C.Init SteamInfo
// (Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent)

void APC_Zombie_C::Init_SteamInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "Init SteamInfo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PC_Zombie.PC_Zombie_C.InitHudCharacter
// (Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent)

void APC_Zombie_C::InitHudCharacter()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "InitHudCharacter");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PC_Zombie.PC_Zombie_C.InitHudPC
// (Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent)

void APC_Zombie_C::InitHudPC()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "InitHudPC");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PC_Zombie.PC_Zombie_C.InitScoreBoard
// (Public, BlueprintCallable, BlueprintEvent)

void APC_Zombie_C::InitScoreBoard()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "InitScoreBoard");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PC_Zombie.PC_Zombie_C.InpActEvt_Escape_K2Node_InputKeyEvent_0
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APC_Zombie_C::InpActEvt_Escape_K2Node_InputKeyEvent_0(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "InpActEvt_Escape_K2Node_InputKeyEvent_0");

	Params::PC_Zombie_C_InpActEvt_Escape_K2Node_InputKeyEvent_0 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.InpActEvt_IA_Score_K2Node_EnhancedInputActionEvent_0
// (BlueprintEvent)
// Parameters:
// struct FInputActionValue                ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UInputAction*                     SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::InpActEvt_IA_Score_K2Node_EnhancedInputActionEvent_0(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "InpActEvt_IA_Score_K2Node_EnhancedInputActionEvent_0");

	Params::PC_Zombie_C_InpActEvt_IA_Score_K2Node_EnhancedInputActionEvent_0 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.InpActEvt_IA_Score_K2Node_EnhancedInputActionEvent_1
// (BlueprintEvent)
// Parameters:
// struct FInputActionValue                ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UInputAction*                     SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::InpActEvt_IA_Score_K2Node_EnhancedInputActionEvent_1(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "InpActEvt_IA_Score_K2Node_EnhancedInputActionEvent_1");

	Params::PC_Zombie_C_InpActEvt_IA_Score_K2Node_EnhancedInputActionEvent_1 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.IsDead
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Dead_                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::IsDead(bool* Dead_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "IsDead");

	Params::PC_Zombie_C_IsDead Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Dead_ != nullptr)
		*Dead_ = Parms.Dead_;
}


// Function PC_Zombie.PC_Zombie_C.IsDestroyabe?
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Destroyable_                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::IsDestroyabe_(bool* Destroyable_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "IsDestroyabe?");

	Params::PC_Zombie_C_IsDestroyabe_ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Destroyable_ != nullptr)
		*Destroyable_ = Parms.Destroyable_;
}


// Function PC_Zombie.PC_Zombie_C.IsReady?
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsReady__0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::IsReady_(bool IsReady__0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "IsReady?");

	Params::PC_Zombie_C_IsReady_ Parms{};

	Parms.IsReady__0 = IsReady__0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.IsSpawnValid
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FTransform                       Spawn_Transform                                        (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Valid_                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::IsSpawnValid(const struct FTransform& Spawn_Transform, bool* Valid_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "IsSpawnValid");

	Params::PC_Zombie_C_IsSpawnValid Parms{};

	Parms.Spawn_Transform = std::move(Spawn_Transform);

	UObject::ProcessEvent(Func, &Parms);

	if (Valid_ != nullptr)
		*Valid_ = Parms.Valid_;
}


// Function PC_Zombie.PC_Zombie_C.IsStress
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Yes_                                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::IsStress(bool* Yes_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "IsStress");

	Params::PC_Zombie_C_IsStress Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Yes_ != nullptr)
		*Yes_ = Parms.Yes_;
}


// Function PC_Zombie.PC_Zombie_C.IsTalking?
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsTalking__0                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::IsTalking_(bool* IsTalking__0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "IsTalking?");

	Params::PC_Zombie_C_IsTalking_ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsTalking__0 != nullptr)
		*IsTalking__0 = Parms.IsTalking__0;
}


// Function PC_Zombie.PC_Zombie_C.j server
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void APC_Zombie_C::J_server()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "j server");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PC_Zombie.PC_Zombie_C.Kick?
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FSTR_PCInfo                      Target                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void APC_Zombie_C::Kick_(const struct FSTR_PCInfo& Target)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "Kick?");

	Params::PC_Zombie_C_Kick_ Parms{};

	Parms.Target = std::move(Target);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.KickPlayer
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FSTR_KickVote                    PlayerInfo                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void APC_Zombie_C::KickPlayer(const struct FSTR_KickVote& PlayerInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "KickPlayer");

	Params::PC_Zombie_C_KickPlayer Parms{};

	Parms.PlayerInfo = std::move(PlayerInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.MSG_AVP_GetPlayerUsername
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Success_                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             Username                                               (Parm, OutParm)

void APC_Zombie_C::MSG_AVP_GetPlayerUsername(bool* Success_, class FText* Username)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "MSG_AVP_GetPlayerUsername");

	Params::PC_Zombie_C_MSG_AVP_GetPlayerUsername Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Success_ != nullptr)
		*Success_ = Parms.Success_;

	if (Username != nullptr)
		*Username = std::move(Parms.Username);
}


// Function PC_Zombie.PC_Zombie_C.MSG_AVP_GetWidgetVoice
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidgetComponent*                 WidgetVoiceRef                                         (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::MSG_AVP_GetWidgetVoice(class UWidgetComponent** WidgetVoiceRef)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "MSG_AVP_GetWidgetVoice");

	Params::PC_Zombie_C_MSG_AVP_GetWidgetVoice Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (WidgetVoiceRef != nullptr)
		*WidgetVoiceRef = Parms.WidgetVoiceRef;
}


// Function PC_Zombie.PC_Zombie_C.MSG_ChatGetConnectedPlayers
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class AController*>              Players                                                (Parm, OutParm)

void APC_Zombie_C::MSG_ChatGetConnectedPlayers(TArray<class AController*>* Players)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "MSG_ChatGetConnectedPlayers");

	Params::PC_Zombie_C_MSG_ChatGetConnectedPlayers Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Players != nullptr)
		*Players = std::move(Parms.Players);
}


// Function PC_Zombie.PC_Zombie_C.MSG_ChatGetPlayerID
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   PlayerID                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::MSG_ChatGetPlayerID(int32* PlayerID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "MSG_ChatGetPlayerID");

	Params::PC_Zombie_C_MSG_ChatGetPlayerID Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (PlayerID != nullptr)
		*PlayerID = Parms.PlayerID;
}


// Function PC_Zombie.PC_Zombie_C.MSG_ChatGetTeamID
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TeamID                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::MSG_ChatGetTeamID(int32* TeamID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "MSG_ChatGetTeamID");

	Params::PC_Zombie_C_MSG_ChatGetTeamID Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (TeamID != nullptr)
		*TeamID = Parms.TeamID;
}


// Function PC_Zombie.PC_Zombie_C.MSG_ChatGetUsername
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Success_                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             Username                                               (Parm, OutParm)

void APC_Zombie_C::MSG_ChatGetUsername(bool* Success_, class FText* Username)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "MSG_ChatGetUsername");

	Params::PC_Zombie_C_MSG_ChatGetUsername Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Success_ != nullptr)
		*Success_ = Parms.Success_;

	if (Username != nullptr)
		*Username = std::move(Parms.Username);
}


// Function PC_Zombie.PC_Zombie_C.MSG_ChatPlayEmote
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// E_Emote                                 EmoteToPlay                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::MSG_ChatPlayEmote(E_Emote EmoteToPlay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "MSG_ChatPlayEmote");

	Params::PC_Zombie_C_MSG_ChatPlayEmote Parms{};

	Parms.EmoteToPlay = EmoteToPlay;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.MSG_ChatRequestPlayerID
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   PlayerID                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Success_                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::MSG_ChatRequestPlayerID(int32* PlayerID, bool* Success_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "MSG_ChatRequestPlayerID");

	Params::PC_Zombie_C_MSG_ChatRequestPlayerID Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (PlayerID != nullptr)
		*PlayerID = Parms.PlayerID;

	if (Success_ != nullptr)
		*Success_ = Parms.Success_;
}


// Function PC_Zombie.PC_Zombie_C.MuteID
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           SteamID                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void APC_Zombie_C::MuteID(const class FString& SteamID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "MuteID");

	Params::PC_Zombie_C_MuteID Parms{};

	Parms.SteamID = std::move(SteamID);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.NewKickVote
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FSTR_PCInfo                      Target                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void APC_Zombie_C::NewKickVote(const struct FSTR_PCInfo& Target)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "NewKickVote");

	Params::PC_Zombie_C_NewKickVote Parms{};

	Parms.Target = std::move(Target);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.NewWaves
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Wave_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EN_WaveClass                            EN_WaveClass                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::NewWaves(int32 Wave_0, EN_WaveClass EN_WaveClass)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "NewWaves");

	Params::PC_Zombie_C_NewWaves Parms{};

	Parms.Wave_0 = Wave_0;
	Parms.EN_WaveClass = EN_WaveClass;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.OnPlayerDeath
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerController*                PC                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::OnPlayerDeath(class APlayerController* PC)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "OnPlayerDeath");

	Params::PC_Zombie_C_OnPlayerDeath Parms{};

	Parms.PC = PC;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.OnTrySelectTeam
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// E_Team                                  Team_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::OnTrySelectTeam(E_Team Team_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "OnTrySelectTeam");

	Params::PC_Zombie_C_OnTrySelectTeam Parms{};

	Parms.Team_0 = Team_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void APC_Zombie_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PC_Zombie.PC_Zombie_C.ReceivePossess
// (Event, Protected, BlueprintEvent)
// Parameters:
// class APawn*                            PossessedPawn                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::ReceivePossess(class APawn* PossessedPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "ReceivePossess");

	Params::PC_Zombie_C_ReceivePossess Parms{};

	Parms.PossessedPawn = PossessedPawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.ReceiveUnPossess
// (Event, Protected, BlueprintEvent)
// Parameters:
// class APawn*                            UnpossessedPawn                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::ReceiveUnPossess(class APawn* UnpossessedPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "ReceiveUnPossess");

	Params::PC_Zombie_C_ReceiveUnPossess Parms{};

	Parms.UnpossessedPawn = UnpossessedPawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.Respawn (Server)
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Respawn_                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::Respawn__Server_(bool Respawn_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "Respawn (Server)");

	Params::PC_Zombie_C_Respawn__Server_ Parms{};

	Parms.Respawn_ = Respawn_;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.RespawnCloseToFriend
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FTransform                       FarestTransform_return                                 (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::RespawnCloseToFriend(struct FTransform* FarestTransform_return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "RespawnCloseToFriend");

	Params::PC_Zombie_C_RespawnCloseToFriend Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FarestTransform_return != nullptr)
		*FarestTransform_return = std::move(Parms.FarestTransform_return);
}


// Function PC_Zombie.PC_Zombie_C.Screamer (Client)
// (Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Destroy_                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::Screamer__Client_(bool Destroy_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "Screamer (Client)");

	Params::PC_Zombie_C_Screamer__Client_ Parms{};

	Parms.Destroy_ = Destroy_;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.ServerTravel
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Delay                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::ServerTravel(double Delay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "ServerTravel");

	Params::PC_Zombie_C_ServerTravel Parms{};

	Parms.Delay = Delay;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.SetSteamID (Server)
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           PCInfo                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// struct FSTR_PCStats                     Item_Stats                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::SetSteamID__Server_(const class FString& PCInfo, const struct FSTR_PCStats& Item_Stats)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "SetSteamID (Server)");

	Params::PC_Zombie_C_SetSteamID__Server_ Parms{};

	Parms.PCInfo = std::move(PCInfo);
	Parms.Item_Stats = std::move(Item_Stats);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.Slomo
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Slomo_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::Slomo(double Slomo_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "Slomo");

	Params::PC_Zombie_C_Slomo Parms{};

	Parms.Slomo_0 = Slomo_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.SpawnDeadCamera
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void APC_Zombie_C::SpawnDeadCamera()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "SpawnDeadCamera");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PC_Zombie.PC_Zombie_C.SpawnScreamer
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Destroy_                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::SpawnScreamer(bool Destroy_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "SpawnScreamer");

	Params::PC_Zombie_C_SpawnScreamer Parms{};

	Parms.Destroy_ = Destroy_;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.SpawnWinHud
// (Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Wave_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Chrono                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::SpawnWinHud(int32 Wave_0, double Chrono)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "SpawnWinHud");

	Params::PC_Zombie_C_SpawnWinHud Parms{};

	Parms.Wave_0 = Wave_0;
	Parms.Chrono = Chrono;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.SpawnZombieEvent
// (Public, BlueprintCallable, BlueprintEvent)

void APC_Zombie_C::SpawnZombieEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "SpawnZombieEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PC_Zombie.PC_Zombie_C.Talk
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsTalking                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::Talk(bool IsTalking)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "Talk");

	Params::PC_Zombie_C_Talk Parms{};

	Parms.IsTalking = IsTalking;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.Update ControlRotation
// (Net, NetReliable, HasOutParams, NetClient, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FRotator                         NewRotation                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor)

void APC_Zombie_C::Update_ControlRotation(const struct FRotator& NewRotation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "Update ControlRotation");

	Params::PC_Zombie_C_Update_ControlRotation Parms{};

	Parms.NewRotation = std::move(NewRotation);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.Update Death
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Death_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Set                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::Update_Death(int32 Death_0, bool Set)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "Update Death");

	Params::PC_Zombie_C_Update_Death Parms{};

	Parms.Death_0 = Death_0;
	Parms.Set = Set;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.Update Death (server)
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void APC_Zombie_C::Update_Death__server_()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "Update Death (server)");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PC_Zombie.PC_Zombie_C.Update Kill
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Kill_                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::Update_Kill(int32 Kill_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "Update Kill");

	Params::PC_Zombie_C_Update_Kill Parms{};

	Parms.Kill_ = Kill_;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.Update ScoreBoard (HUD)
// (Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Remove_                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::Update_ScoreBoard__HUD_(bool Remove_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "Update ScoreBoard (HUD)");

	Params::PC_Zombie_C_Update_ScoreBoard__HUD_ Parms{};

	Parms.Remove_ = Remove_;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.UpdateGamemode
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EGameMode                               GameMode                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::UpdateGamemode(EGameMode GameMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "UpdateGamemode");

	Params::PC_Zombie_C_UpdateGamemode Parms{};

	Parms.GameMode = GameMode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.UpdateKickVote
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FSTR_PCInfo                      Target                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// bool                                    Yes_                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::UpdateKickVote(const struct FSTR_PCInfo& Target, bool Yes_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "UpdateKickVote");

	Params::PC_Zombie_C_UpdateKickVote Parms{};

	Parms.Target = std::move(Target);
	Parms.Yes_ = Yes_;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.UpdateKill (Server)
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Kill                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::UpdateKill__Server_(int32 Kill)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "UpdateKill (Server)");

	Params::PC_Zombie_C_UpdateKill__Server_ Parms{};

	Parms.Kill = Kill;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.UpdateMapSelection
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             Selected_Level_Name                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::UpdateMapSelection(class FName Selected_Level_Name, int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "UpdateMapSelection");

	Params::PC_Zombie_C_UpdateMapSelection Parms{};

	Parms.Selected_Level_Name = Selected_Level_Name;
	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.UpdateModeInfo
// (Public, BlueprintCallable, BlueprintEvent)

void APC_Zombie_C::UpdateModeInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "UpdateModeInfo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PC_Zombie.PC_Zombie_C.UpdatePower
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    On_                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::UpdatePower(bool On_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "UpdatePower");

	Params::PC_Zombie_C_UpdatePower Parms{};

	Parms.On_ = On_;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.UpdateScore
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FSTR_Score                       Score                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::UpdateScore(const struct FSTR_Score& Score)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "UpdateScore");

	Params::PC_Zombie_C_UpdateScore Parms{};

	Parms.Score = std::move(Score);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.UpdateTeamIndex (PlayerKilled)
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// E_Team                                  Team_PlayerKilled_                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   MilitaryIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   TerroristIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// E_Team                                  WiiningTeam                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::UpdateTeamIndex__PlayerKilled_(E_Team Team_PlayerKilled_, int32 MilitaryIndex, int32 TerroristIndex, E_Team WiiningTeam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "UpdateTeamIndex (PlayerKilled)");

	Params::PC_Zombie_C_UpdateTeamIndex__PlayerKilled_ Parms{};

	Parms.Team_PlayerKilled_ = Team_PlayerKilled_;
	Parms.MilitaryIndex = MilitaryIndex;
	Parms.TerroristIndex = TerroristIndex;
	Parms.WiiningTeam = WiiningTeam;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.UpdateTeamXP
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Win_                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::UpdateTeamXP(bool Win_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "UpdateTeamXP");

	Params::PC_Zombie_C_UpdateTeamXP Parms{};

	Parms.Win_ = Win_;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.UpdateTimer
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  TimeCount                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm)

void APC_Zombie_C::UpdateTimer(double TimeCount, const class FText& NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "UpdateTimer");

	Params::PC_Zombie_C_UpdateTimer Parms{};

	Parms.TimeCount = TimeCount;
	Parms.NewParam = std::move(NewParam);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.UpdateTransitionMap
// (Public, BlueprintCallable, BlueprintEvent)

void APC_Zombie_C::UpdateTransitionMap()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "UpdateTransitionMap");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PC_Zombie.PC_Zombie_C.UpdateWarning
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           String                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void APC_Zombie_C::UpdateWarning(const class FString& String)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "UpdateWarning");

	Params::PC_Zombie_C_UpdateWarning Parms{};

	Parms.String = std::move(String);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PC_Zombie.PC_Zombie_C.UpdateXp
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Xp                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APC_Zombie_C::UpdateXp(int32 Xp)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PC_Zombie_C", "UpdateXp");

	Params::PC_Zombie_C_UpdateXp Parms{};

	Parms.Xp = Xp;

	UObject::ProcessEvent(Func, &Parms);
}

}

