#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Remington

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK
{

// ScriptStruct Remington.Remington_C.AnimBlueprintGeneratedConstantData
// 0x00CF (0x00D0 - 0x0001)
struct Remington::FAnimBlueprintGeneratedConstantData final : public FAnimBlueprintConstantData
{
public:
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNodeFunctionRef                   __StructProperty_4;                                // 0x0008(0x0020)(BlueprintVisible, NoDestructor)
	class FName                                   __NameProperty_5;                                  // 0x0028(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_6;                                  // 0x0030(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAnimSubsystem_PropertyAccess          AnimBlueprintExtension_PropertyAccess;             // 0x0038(0x0080)()
	struct FAnimSubsystem_Base                    AnimBlueprintExtension_Base;                       // 0x00B8(0x0018)()
};
static_assert(alignof(Remington::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on Remington::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(Remington::FAnimBlueprintGeneratedConstantData) == 0x0000D0, "Wrong size on Remington::FAnimBlueprintGeneratedConstantData");
static_assert(offsetof(Remington::FAnimBlueprintGeneratedConstantData, __StructProperty_4) == 0x000008, "Member 'Remington::FAnimBlueprintGeneratedConstantData::__StructProperty_4' has a wrong offset!");
static_assert(offsetof(Remington::FAnimBlueprintGeneratedConstantData, __NameProperty_5) == 0x000028, "Member 'Remington::FAnimBlueprintGeneratedConstantData::__NameProperty_5' has a wrong offset!");
static_assert(offsetof(Remington::FAnimBlueprintGeneratedConstantData, __NameProperty_6) == 0x000030, "Member 'Remington::FAnimBlueprintGeneratedConstantData::__NameProperty_6' has a wrong offset!");
static_assert(offsetof(Remington::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_PropertyAccess) == 0x000038, "Member 'Remington::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(Remington::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_Base) == 0x0000B8, "Member 'Remington::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_Base' has a wrong offset!");

}

