#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ServerSlotEN

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum ServerSlotEN.ServerSlotEN
// NumValues: 0x0006
enum class EServerSlotEN : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	NewEnumerator4                           = 4,
	ServerSlotEN_MAX                         = 5,
};

}

