#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SpectatorHud

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "STR_PCInfo_structs.hpp"
#include "WBP_InteractableMenu_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SpectatorHud.SpectatorHud_C
// 0x0088 (0x0410 - 0x0388)
class USpectatorHud_C final : public UWBP_InteractableMenu_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_SpectatorHud_C;                     // 0x0388(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Hide;                                              // 0x0390(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Init;                                              // 0x0398(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UOverlay*                               GAMEINFO;                                          // 0x03A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 VHS_TEX;                                           // 0x03A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Vhs_C*                             WBP_Vhs;                                           // 0x03B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FSTR_PCInfo                            Current_Viewed_Info;                               // 0x03B8(0x0040)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	TArray<struct FSTR_PCInfo>                    Team_Info;                                         // 0x03F8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UMediaPlayer*                           MediaPlayerTarget;                                 // 0x0408(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void Construct();
	void ExecuteUbergraph_SpectatorHud(int32 EntryPoint);
	void HideSpectatorHud();
	void SwitchPlayers();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SpectatorHud_C">();
	}
	static class USpectatorHud_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USpectatorHud_C>();
	}
};
static_assert(alignof(USpectatorHud_C) == 0x000008, "Wrong alignment on USpectatorHud_C");
static_assert(sizeof(USpectatorHud_C) == 0x000410, "Wrong size on USpectatorHud_C");
static_assert(offsetof(USpectatorHud_C, UberGraphFrame_SpectatorHud_C) == 0x000388, "Member 'USpectatorHud_C::UberGraphFrame_SpectatorHud_C' has a wrong offset!");
static_assert(offsetof(USpectatorHud_C, Hide) == 0x000390, "Member 'USpectatorHud_C::Hide' has a wrong offset!");
static_assert(offsetof(USpectatorHud_C, Init) == 0x000398, "Member 'USpectatorHud_C::Init' has a wrong offset!");
static_assert(offsetof(USpectatorHud_C, GAMEINFO) == 0x0003A0, "Member 'USpectatorHud_C::GAMEINFO' has a wrong offset!");
static_assert(offsetof(USpectatorHud_C, VHS_TEX) == 0x0003A8, "Member 'USpectatorHud_C::VHS_TEX' has a wrong offset!");
static_assert(offsetof(USpectatorHud_C, WBP_Vhs) == 0x0003B0, "Member 'USpectatorHud_C::WBP_Vhs' has a wrong offset!");
static_assert(offsetof(USpectatorHud_C, Current_Viewed_Info) == 0x0003B8, "Member 'USpectatorHud_C::Current_Viewed_Info' has a wrong offset!");
static_assert(offsetof(USpectatorHud_C, Team_Info) == 0x0003F8, "Member 'USpectatorHud_C::Team_Info' has a wrong offset!");
static_assert(offsetof(USpectatorHud_C, MediaPlayerTarget) == 0x000408, "Member 'USpectatorHud_C::MediaPlayerTarget' has a wrong offset!");

}

