#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: STR_ANIMATIONS

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct STR_ANIMATIONS.STR_ANIMATIONS
// 0x0010 (0x0010 - 0x0000)
struct FSTR_ANIMATIONS final
{
public:
	class UAnimMontage*                           Body_2_DA9112CD409AD676AD61B3B50F574AD1;           // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           Wep_4_8CA432DA4CDE152CC0A02FBD75EB6439;            // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FSTR_ANIMATIONS) == 0x000008, "Wrong alignment on FSTR_ANIMATIONS");
static_assert(sizeof(FSTR_ANIMATIONS) == 0x000010, "Wrong size on FSTR_ANIMATIONS");
static_assert(offsetof(FSTR_ANIMATIONS, Body_2_DA9112CD409AD676AD61B3B50F574AD1) == 0x000000, "Member 'FSTR_ANIMATIONS::Body_2_DA9112CD409AD676AD61B3B50F574AD1' has a wrong offset!");
static_assert(offsetof(FSTR_ANIMATIONS, Wep_4_8CA432DA4CDE152CC0A02FBD75EB6439) == 0x000008, "Member 'FSTR_ANIMATIONS::Wep_4_8CA432DA4CDE152CC0A02FBD75EB6439' has a wrong offset!");

}

