#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UDS_Occlusion_Volume_Interface

#include "Basic.hpp"


namespace SDK::Params
{

// Function UDS_Occlusion_Volume_Interface.UDS_Occlusion_Volume_Interface_C.Get Occlusion Result
// 0x0002 (0x0002 - 0x0000)
struct UDS_Occlusion_Volume_Interface_C_Get_Occlusion_Result final
{
public:
	bool                                          Weather;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Occluded;                                          // 0x0001(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UDS_Occlusion_Volume_Interface_C_Get_Occlusion_Result) == 0x000001, "Wrong alignment on UDS_Occlusion_Volume_Interface_C_Get_Occlusion_Result");
static_assert(sizeof(UDS_Occlusion_Volume_Interface_C_Get_Occlusion_Result) == 0x000002, "Wrong size on UDS_Occlusion_Volume_Interface_C_Get_Occlusion_Result");
static_assert(offsetof(UDS_Occlusion_Volume_Interface_C_Get_Occlusion_Result, Weather) == 0x000000, "Member 'UDS_Occlusion_Volume_Interface_C_Get_Occlusion_Result::Weather' has a wrong offset!");
static_assert(offsetof(UDS_Occlusion_Volume_Interface_C_Get_Occlusion_Result, Occluded) == 0x000001, "Member 'UDS_Occlusion_Volume_Interface_C_Get_Occlusion_Result::Occluded' has a wrong offset!");

}

