#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_CommonCheckbox

#include "Basic.hpp"


namespace SDK::Params
{

// Function UI_CommonCheckbox.UI_CommonCheckbox_C.BndEvt__CheckBox_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct UI_CommonCheckbox_C_BndEvt__CheckBox_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature final
{
public:
	bool                                          bIsChecked;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_CommonCheckbox_C_BndEvt__CheckBox_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature) == 0x000001, "Wrong alignment on UI_CommonCheckbox_C_BndEvt__CheckBox_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature");
static_assert(sizeof(UI_CommonCheckbox_C_BndEvt__CheckBox_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature) == 0x000001, "Wrong size on UI_CommonCheckbox_C_BndEvt__CheckBox_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature");
static_assert(offsetof(UI_CommonCheckbox_C_BndEvt__CheckBox_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature, bIsChecked) == 0x000000, "Member 'UI_CommonCheckbox_C_BndEvt__CheckBox_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature::bIsChecked' has a wrong offset!");

// Function UI_CommonCheckbox.UI_CommonCheckbox_C.ExecuteUbergraph_UI_CommonCheckbox
// 0x0008 (0x0008 - 0x0000)
struct UI_CommonCheckbox_C_ExecuteUbergraph_UI_CommonCheckbox final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bIsChecked;             // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_CommonCheckbox_C_ExecuteUbergraph_UI_CommonCheckbox) == 0x000004, "Wrong alignment on UI_CommonCheckbox_C_ExecuteUbergraph_UI_CommonCheckbox");
static_assert(sizeof(UI_CommonCheckbox_C_ExecuteUbergraph_UI_CommonCheckbox) == 0x000008, "Wrong size on UI_CommonCheckbox_C_ExecuteUbergraph_UI_CommonCheckbox");
static_assert(offsetof(UI_CommonCheckbox_C_ExecuteUbergraph_UI_CommonCheckbox, EntryPoint) == 0x000000, "Member 'UI_CommonCheckbox_C_ExecuteUbergraph_UI_CommonCheckbox::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_CommonCheckbox_C_ExecuteUbergraph_UI_CommonCheckbox, K2Node_ComponentBoundEvent_bIsChecked) == 0x000004, "Member 'UI_CommonCheckbox_C_ExecuteUbergraph_UI_CommonCheckbox::K2Node_ComponentBoundEvent_bIsChecked' has a wrong offset!");
static_assert(offsetof(UI_CommonCheckbox_C_ExecuteUbergraph_UI_CommonCheckbox, K2Node_Event_IsDesignTime) == 0x000005, "Member 'UI_CommonCheckbox_C_ExecuteUbergraph_UI_CommonCheckbox::K2Node_Event_IsDesignTime' has a wrong offset!");

// Function UI_CommonCheckbox.UI_CommonCheckbox_C.Is Checked
// 0x0002 (0x0002 - 0x0000)
struct UI_CommonCheckbox_C_Is_Checked final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsChecked_ReturnValue;                    // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_CommonCheckbox_C_Is_Checked) == 0x000001, "Wrong alignment on UI_CommonCheckbox_C_Is_Checked");
static_assert(sizeof(UI_CommonCheckbox_C_Is_Checked) == 0x000002, "Wrong size on UI_CommonCheckbox_C_Is_Checked");
static_assert(offsetof(UI_CommonCheckbox_C_Is_Checked, ReturnValue) == 0x000000, "Member 'UI_CommonCheckbox_C_Is_Checked::ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_CommonCheckbox_C_Is_Checked, CallFunc_IsChecked_ReturnValue) == 0x000001, "Member 'UI_CommonCheckbox_C_Is_Checked::CallFunc_IsChecked_ReturnValue' has a wrong offset!");

// Function UI_CommonCheckbox.UI_CommonCheckbox_C.OnStateChanged__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct UI_CommonCheckbox_C_OnStateChanged__DelegateSignature final
{
public:
	bool                                          IsChecked;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_CommonCheckbox_C_OnStateChanged__DelegateSignature) == 0x000001, "Wrong alignment on UI_CommonCheckbox_C_OnStateChanged__DelegateSignature");
static_assert(sizeof(UI_CommonCheckbox_C_OnStateChanged__DelegateSignature) == 0x000001, "Wrong size on UI_CommonCheckbox_C_OnStateChanged__DelegateSignature");
static_assert(offsetof(UI_CommonCheckbox_C_OnStateChanged__DelegateSignature, IsChecked) == 0x000000, "Member 'UI_CommonCheckbox_C_OnStateChanged__DelegateSignature::IsChecked' has a wrong offset!");

// Function UI_CommonCheckbox.UI_CommonCheckbox_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_CommonCheckbox_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_CommonCheckbox_C_PreConstruct) == 0x000001, "Wrong alignment on UI_CommonCheckbox_C_PreConstruct");
static_assert(sizeof(UI_CommonCheckbox_C_PreConstruct) == 0x000001, "Wrong size on UI_CommonCheckbox_C_PreConstruct");
static_assert(offsetof(UI_CommonCheckbox_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'UI_CommonCheckbox_C_PreConstruct::IsDesignTime' has a wrong offset!");

}

