#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ComboBoxOptions

#include "Basic.hpp"


namespace SDK::Params
{

// Function UI_ComboBoxOptions.UI_ComboBoxOptions_C.AddOption
// 0x0010 (0x0010 - 0x0000)
struct UI_ComboBoxOptions_C_AddOption final
{
public:
	class FString                                 NewItem;                                           // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, HasGetValueTypeHash)
};
static_assert(alignof(UI_ComboBoxOptions_C_AddOption) == 0x000008, "Wrong alignment on UI_ComboBoxOptions_C_AddOption");
static_assert(sizeof(UI_ComboBoxOptions_C_AddOption) == 0x000010, "Wrong size on UI_ComboBoxOptions_C_AddOption");
static_assert(offsetof(UI_ComboBoxOptions_C_AddOption, NewItem) == 0x000000, "Member 'UI_ComboBoxOptions_C_AddOption::NewItem' has a wrong offset!");

// Function UI_ComboBoxOptions.UI_ComboBoxOptions_C.ExecuteUbergraph_UI_ComboBoxOptions
// 0x01B0 (0x01B0 - 0x0000)
struct UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_ComboBoxSingle_C*                   CallFunc_Create_ReturnValue;                       // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_22[0x2];                                       // 0x0022(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_CustomEvent_FilterKey;                      // 0x0038(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsEmpty_ReturnValue;                      // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         CallFunc_Map_Keys_Keys;                            // 0x0050(0x0010)(ReferenceParm)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Array_Get_Item;                           // 0x0068(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_Contains_ReturnValue;                     // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_79[0x3];                                       // 0x0079(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0081(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_82[0x6];                                       // 0x0082(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_ComboBoxSingle_C*                   CallFunc_Map_Find_Value;                           // 0x0088(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0091(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_92[0x2];                                       // 0x0092(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class FString>                         CallFunc_Map_Keys_Keys_1;                          // 0x0098(0x0010)(ReferenceParm)
	class FString                                 CallFunc_Array_Get_Item_1;                         // 0x00A8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_BC[0x4];                                       // 0x00BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_CustomEvent_Option;                         // 0x00C0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UUI_ComboBoxSingle_C*                   CallFunc_Map_Find_Value_1;                         // 0x00D0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_1;                   // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D9[0x3];                                       // 0x00D9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x00DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E1[0x7];                                       // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         K2Node_CustomEvent_Options;                        // 0x00E8(0x0010)(ConstParm, ReferenceParm)
	class FString                                 K2Node_CustomEvent_NewItem;                        // 0x00F8(0x0010)(ConstParm, ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0108(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_10C[0x4];                                      // 0x010C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         K2Node_CustomEvent_Array;                          // 0x0110(0x0010)(ConstParm, ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue_3;               // 0x0120(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0124(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_125[0x3];                                      // 0x0125(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_CustomEvent_CurrentOption;                  // 0x0128(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UUI_ComboBoxSingle_C*                   CallFunc_Map_Find_Value_2;                         // 0x0138(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_2;                   // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0141(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_142[0x6];                                      // 0x0142(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_ComboBoxSingle_C*                   CallFunc_Map_Find_Value_3;                         // 0x0148(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_3;                   // 0x0150(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_151[0x3];                                      // 0x0151(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x0154(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x0158(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_159[0x3];                                      // 0x0159(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x015C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0160(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_161[0x3];                                      // 0x0161(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_4;               // 0x0164(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_1;             // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_169[0x7];                                      // 0x0169(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_ComboBoxSingle_C*                   CallFunc_Create_ReturnValue_1;                     // 0x0170(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue_1;                   // 0x0178(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_RandomFloatInRange_ReturnValue;           // 0x0180(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUI_ComboBoxSingle_C*                   CallFunc_Map_Find_Value_4;                         // 0x0188(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_4;                   // 0x0190(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0191(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_192[0x2];                                      // 0x0192(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x0194(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Array_Get_Item_2;                         // 0x0198(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	float                                         CallFunc_SetHeightOverride_InHeightOverride_ImplicitCast; // 0x01A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Delay_Duration_ImplicitCast;              // 0x01AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions) == 0x000008, "Wrong alignment on UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions");
static_assert(sizeof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions) == 0x0001B0, "Wrong size on UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, EntryPoint) == 0x000000, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Create_ReturnValue) == 0x000008, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, Temp_int_Loop_Counter_Variable) == 0x000010, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Add_IntInt_ReturnValue) == 0x000014, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, Temp_bool_True_if_break_was_hit_Variable) == 0x000018, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::Temp_bool_True_if_break_was_hit_Variable' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, Temp_int_Array_Index_Variable) == 0x00001C, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Not_PreBool_ReturnValue) == 0x000020, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, K2Node_Event_IsDesignTime) == 0x000021, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, Temp_int_Loop_Counter_Variable_1) == 0x000024, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_AddChild_ReturnValue) == 0x000028, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_AddChild_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Add_IntInt_ReturnValue_1) == 0x000030, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, K2Node_CustomEvent_FilterKey) == 0x000038, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::K2Node_CustomEvent_FilterKey' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_IsEmpty_ReturnValue) == 0x000048, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_IsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Map_Keys_Keys) == 0x000050, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Map_Keys_Keys' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Not_PreBool_ReturnValue_1) == 0x000060, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Array_Get_Item) == 0x000068, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Contains_ReturnValue) == 0x000078, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Contains_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Array_Length_ReturnValue) == 0x00007C, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Less_IntInt_ReturnValue) == 0x000080, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_BooleanAND_ReturnValue) == 0x000081, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Map_Find_Value) == 0x000088, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Map_Find_ReturnValue) == 0x000090, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_IsValid_ReturnValue) == 0x000091, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, Temp_int_Array_Index_Variable_1) == 0x000094, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Map_Keys_Keys_1) == 0x000098, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Map_Keys_Keys_1' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Array_Get_Item_1) == 0x0000A8, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Array_Length_ReturnValue_1) == 0x0000B8, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, K2Node_CustomEvent_Option) == 0x0000C0, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::K2Node_CustomEvent_Option' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Map_Find_Value_1) == 0x0000D0, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Map_Find_Value_1' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Map_Find_ReturnValue_1) == 0x0000D8, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Map_Find_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Array_Length_ReturnValue_2) == 0x0000DC, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Greater_IntInt_ReturnValue) == 0x0000E0, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, K2Node_CustomEvent_Options) == 0x0000E8, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::K2Node_CustomEvent_Options' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, K2Node_CustomEvent_NewItem) == 0x0000F8, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::K2Node_CustomEvent_NewItem' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Array_Add_ReturnValue) == 0x000108, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, K2Node_CustomEvent_Array) == 0x000110, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::K2Node_CustomEvent_Array' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Array_Length_ReturnValue_3) == 0x000120, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Array_Length_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Less_IntInt_ReturnValue_1) == 0x000124, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, K2Node_CustomEvent_CurrentOption) == 0x000128, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::K2Node_CustomEvent_CurrentOption' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Map_Find_Value_2) == 0x000138, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Map_Find_Value_2' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Map_Find_ReturnValue_2) == 0x000140, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Map_Find_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_IsValid_ReturnValue_1) == 0x000141, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Map_Find_Value_3) == 0x000148, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Map_Find_Value_3' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Map_Find_ReturnValue_3) == 0x000150, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Map_Find_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, Temp_int_Loop_Counter_Variable_2) == 0x000154, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::Temp_int_Loop_Counter_Variable_2' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Less_IntInt_ReturnValue_2) == 0x000158, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Add_IntInt_ReturnValue_2) == 0x00015C, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_IsValid_ReturnValue_2) == 0x000160, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Array_Length_ReturnValue_4) == 0x000164, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Array_Length_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Greater_IntInt_ReturnValue_1) == 0x000168, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Greater_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Create_ReturnValue_1) == 0x000170, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Create_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_AddChild_ReturnValue_1) == 0x000178, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_AddChild_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_RandomFloatInRange_ReturnValue) == 0x000180, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_RandomFloatInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Map_Find_Value_4) == 0x000188, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Map_Find_Value_4' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Map_Find_ReturnValue_4) == 0x000190, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Map_Find_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_IsValid_ReturnValue_3) == 0x000191, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, Temp_int_Array_Index_Variable_2) == 0x000194, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::Temp_int_Array_Index_Variable_2' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Array_Get_Item_2) == 0x000198, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_SetHeightOverride_InHeightOverride_ImplicitCast) == 0x0001A8, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_SetHeightOverride_InHeightOverride_ImplicitCast' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions, CallFunc_Delay_Duration_ImplicitCast) == 0x0001AC, "Member 'UI_ComboBoxOptions_C_ExecuteUbergraph_UI_ComboBoxOptions::CallFunc_Delay_Duration_ImplicitCast' has a wrong offset!");

// Function UI_ComboBoxOptions.UI_ComboBoxOptions_C.FilterOptions
// 0x0010 (0x0010 - 0x0000)
struct UI_ComboBoxOptions_C_FilterOptions final
{
public:
	class FString                                 FilterKey;                                         // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_ComboBoxOptions_C_FilterOptions) == 0x000008, "Wrong alignment on UI_ComboBoxOptions_C_FilterOptions");
static_assert(sizeof(UI_ComboBoxOptions_C_FilterOptions) == 0x000010, "Wrong size on UI_ComboBoxOptions_C_FilterOptions");
static_assert(offsetof(UI_ComboBoxOptions_C_FilterOptions, FilterKey) == 0x000000, "Member 'UI_ComboBoxOptions_C_FilterOptions::FilterKey' has a wrong offset!");

// Function UI_ComboBoxOptions.UI_ComboBoxOptions_C.GenerateOptions
// 0x0010 (0x0010 - 0x0000)
struct UI_ComboBoxOptions_C_GenerateOptions final
{
public:
	TArray<class FString>                         Array;                                             // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(UI_ComboBoxOptions_C_GenerateOptions) == 0x000008, "Wrong alignment on UI_ComboBoxOptions_C_GenerateOptions");
static_assert(sizeof(UI_ComboBoxOptions_C_GenerateOptions) == 0x000010, "Wrong size on UI_ComboBoxOptions_C_GenerateOptions");
static_assert(offsetof(UI_ComboBoxOptions_C_GenerateOptions, Array) == 0x000000, "Member 'UI_ComboBoxOptions_C_GenerateOptions::Array' has a wrong offset!");

// Function UI_ComboBoxOptions.UI_ComboBoxOptions_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_ComboBoxOptions_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_ComboBoxOptions_C_PreConstruct) == 0x000001, "Wrong alignment on UI_ComboBoxOptions_C_PreConstruct");
static_assert(sizeof(UI_ComboBoxOptions_C_PreConstruct) == 0x000001, "Wrong size on UI_ComboBoxOptions_C_PreConstruct");
static_assert(offsetof(UI_ComboBoxOptions_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'UI_ComboBoxOptions_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function UI_ComboBoxOptions.UI_ComboBoxOptions_C.RefreshOptions
// 0x0010 (0x0010 - 0x0000)
struct UI_ComboBoxOptions_C_RefreshOptions final
{
public:
	TArray<class FString>                         Options_0;                                         // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(UI_ComboBoxOptions_C_RefreshOptions) == 0x000008, "Wrong alignment on UI_ComboBoxOptions_C_RefreshOptions");
static_assert(sizeof(UI_ComboBoxOptions_C_RefreshOptions) == 0x000010, "Wrong size on UI_ComboBoxOptions_C_RefreshOptions");
static_assert(offsetof(UI_ComboBoxOptions_C_RefreshOptions, Options_0) == 0x000000, "Member 'UI_ComboBoxOptions_C_RefreshOptions::Options_0' has a wrong offset!");

// Function UI_ComboBoxOptions.UI_ComboBoxOptions_C.UpdateOption
// 0x0010 (0x0010 - 0x0000)
struct UI_ComboBoxOptions_C_UpdateOption final
{
public:
	class FString                                 Option;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_ComboBoxOptions_C_UpdateOption) == 0x000008, "Wrong alignment on UI_ComboBoxOptions_C_UpdateOption");
static_assert(sizeof(UI_ComboBoxOptions_C_UpdateOption) == 0x000010, "Wrong size on UI_ComboBoxOptions_C_UpdateOption");
static_assert(offsetof(UI_ComboBoxOptions_C_UpdateOption, Option) == 0x000000, "Member 'UI_ComboBoxOptions_C_UpdateOption::Option' has a wrong offset!");

// Function UI_ComboBoxOptions.UI_ComboBoxOptions_C.UpdateSelected
// 0x0010 (0x0010 - 0x0000)
struct UI_ComboBoxOptions_C_UpdateSelected final
{
public:
	class FString                                 CurrentOption_0;                                   // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_ComboBoxOptions_C_UpdateSelected) == 0x000008, "Wrong alignment on UI_ComboBoxOptions_C_UpdateSelected");
static_assert(sizeof(UI_ComboBoxOptions_C_UpdateSelected) == 0x000010, "Wrong size on UI_ComboBoxOptions_C_UpdateSelected");
static_assert(offsetof(UI_ComboBoxOptions_C_UpdateSelected, CurrentOption_0) == 0x000000, "Member 'UI_ComboBoxOptions_C_UpdateSelected::CurrentOption_0' has a wrong offset!");

// Function UI_ComboBoxOptions.UI_ComboBoxOptions_C.GetFirstElement
// 0x0058 (0x0058 - 0x0000)
struct UI_ComboBoxOptions_C_GetFirstElement final
{
public:
	bool                                          IsValid;                                           // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Option;                                            // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)
	class UUI_ComboBoxSingle_C*                   OptionReference;                                   // 0x0018(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class FString>                         CallFunc_Map_Keys_Keys;                            // 0x0020(0x0010)(ReferenceParm)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue;           // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Array_Get_Item;                           // 0x0038(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UUI_ComboBoxSingle_C*                   CallFunc_Map_Find_Value;                           // 0x0048(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_ComboBoxOptions_C_GetFirstElement) == 0x000008, "Wrong alignment on UI_ComboBoxOptions_C_GetFirstElement");
static_assert(sizeof(UI_ComboBoxOptions_C_GetFirstElement) == 0x000058, "Wrong size on UI_ComboBoxOptions_C_GetFirstElement");
static_assert(offsetof(UI_ComboBoxOptions_C_GetFirstElement, IsValid) == 0x000000, "Member 'UI_ComboBoxOptions_C_GetFirstElement::IsValid' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_GetFirstElement, Option) == 0x000008, "Member 'UI_ComboBoxOptions_C_GetFirstElement::Option' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_GetFirstElement, OptionReference) == 0x000018, "Member 'UI_ComboBoxOptions_C_GetFirstElement::OptionReference' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_GetFirstElement, CallFunc_Map_Keys_Keys) == 0x000020, "Member 'UI_ComboBoxOptions_C_GetFirstElement::CallFunc_Map_Keys_Keys' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_GetFirstElement, CallFunc_Array_IsValidIndex_ReturnValue) == 0x000030, "Member 'UI_ComboBoxOptions_C_GetFirstElement::CallFunc_Array_IsValidIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_GetFirstElement, CallFunc_Array_Get_Item) == 0x000038, "Member 'UI_ComboBoxOptions_C_GetFirstElement::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_GetFirstElement, CallFunc_Map_Find_Value) == 0x000048, "Member 'UI_ComboBoxOptions_C_GetFirstElement::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(UI_ComboBoxOptions_C_GetFirstElement, CallFunc_Map_Find_ReturnValue) == 0x000050, "Member 'UI_ComboBoxOptions_C_GetFirstElement::CallFunc_Map_Find_ReturnValue' has a wrong offset!");

}

