#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Slot

#include "Basic.hpp"


namespace SDK::Params
{

// Function UI_Slot.UI_Slot_C.ExecuteUbergraph_UI_Slot
// 0x0058 (0x0058 - 0x0000)
struct UI_Slot_C_ExecuteUbergraph_UI_Slot final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_ObjectRender_C*                     CallFunc_GetActorOfClass_ReturnValue;              // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<class UUI_Slot_C*>                     CallFunc_GetAllWidgetsOfClass_FoundWidgets;        // 0x0018(0x0010)(ReferenceParm, ContainsInstancedReference)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_Slot_C*                             CallFunc_Array_Get_Item;                           // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_Show;                           // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3D[0x3];                                       // 0x003D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_SelectFloat_ReturnValue;                  // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x004C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4D[0x3];                                       // 0x004D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetRenderOpacity_InOpacity_ImplicitCast;  // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Slot_C_ExecuteUbergraph_UI_Slot) == 0x000008, "Wrong alignment on UI_Slot_C_ExecuteUbergraph_UI_Slot");
static_assert(sizeof(UI_Slot_C_ExecuteUbergraph_UI_Slot) == 0x000058, "Wrong size on UI_Slot_C_ExecuteUbergraph_UI_Slot");
static_assert(offsetof(UI_Slot_C_ExecuteUbergraph_UI_Slot, EntryPoint) == 0x000000, "Member 'UI_Slot_C_ExecuteUbergraph_UI_Slot::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_Slot_C_ExecuteUbergraph_UI_Slot, Temp_int_Array_Index_Variable) == 0x000004, "Member 'UI_Slot_C_ExecuteUbergraph_UI_Slot::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UI_Slot_C_ExecuteUbergraph_UI_Slot, K2Node_Event_IsDesignTime) == 0x000008, "Member 'UI_Slot_C_ExecuteUbergraph_UI_Slot::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(UI_Slot_C_ExecuteUbergraph_UI_Slot, CallFunc_GetActorOfClass_ReturnValue) == 0x000010, "Member 'UI_Slot_C_ExecuteUbergraph_UI_Slot::CallFunc_GetActorOfClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Slot_C_ExecuteUbergraph_UI_Slot, CallFunc_GetAllWidgetsOfClass_FoundWidgets) == 0x000018, "Member 'UI_Slot_C_ExecuteUbergraph_UI_Slot::CallFunc_GetAllWidgetsOfClass_FoundWidgets' has a wrong offset!");
static_assert(offsetof(UI_Slot_C_ExecuteUbergraph_UI_Slot, CallFunc_IsValid_ReturnValue) == 0x000028, "Member 'UI_Slot_C_ExecuteUbergraph_UI_Slot::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Slot_C_ExecuteUbergraph_UI_Slot, CallFunc_Array_Get_Item) == 0x000030, "Member 'UI_Slot_C_ExecuteUbergraph_UI_Slot::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_Slot_C_ExecuteUbergraph_UI_Slot, CallFunc_Array_Length_ReturnValue) == 0x000038, "Member 'UI_Slot_C_ExecuteUbergraph_UI_Slot::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Slot_C_ExecuteUbergraph_UI_Slot, K2Node_CustomEvent_Show) == 0x00003C, "Member 'UI_Slot_C_ExecuteUbergraph_UI_Slot::K2Node_CustomEvent_Show' has a wrong offset!");
static_assert(offsetof(UI_Slot_C_ExecuteUbergraph_UI_Slot, CallFunc_SelectFloat_ReturnValue) == 0x000040, "Member 'UI_Slot_C_ExecuteUbergraph_UI_Slot::CallFunc_SelectFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Slot_C_ExecuteUbergraph_UI_Slot, Temp_int_Loop_Counter_Variable) == 0x000048, "Member 'UI_Slot_C_ExecuteUbergraph_UI_Slot::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UI_Slot_C_ExecuteUbergraph_UI_Slot, CallFunc_Less_IntInt_ReturnValue) == 0x00004C, "Member 'UI_Slot_C_ExecuteUbergraph_UI_Slot::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Slot_C_ExecuteUbergraph_UI_Slot, CallFunc_Add_IntInt_ReturnValue) == 0x000050, "Member 'UI_Slot_C_ExecuteUbergraph_UI_Slot::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Slot_C_ExecuteUbergraph_UI_Slot, CallFunc_SetRenderOpacity_InOpacity_ImplicitCast) == 0x000054, "Member 'UI_Slot_C_ExecuteUbergraph_UI_Slot::CallFunc_SetRenderOpacity_InOpacity_ImplicitCast' has a wrong offset!");

// Function UI_Slot.UI_Slot_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_Slot_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Slot_C_PreConstruct) == 0x000001, "Wrong alignment on UI_Slot_C_PreConstruct");
static_assert(sizeof(UI_Slot_C_PreConstruct) == 0x000001, "Wrong size on UI_Slot_C_PreConstruct");
static_assert(offsetof(UI_Slot_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'UI_Slot_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function UI_Slot.UI_Slot_C.ShowBorder
// 0x0001 (0x0001 - 0x0000)
struct UI_Slot_C_ShowBorder final
{
public:
	bool                                          Show;                                              // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Slot_C_ShowBorder) == 0x000001, "Wrong alignment on UI_Slot_C_ShowBorder");
static_assert(sizeof(UI_Slot_C_ShowBorder) == 0x000001, "Wrong size on UI_Slot_C_ShowBorder");
static_assert(offsetof(UI_Slot_C_ShowBorder, Show) == 0x000000, "Member 'UI_Slot_C_ShowBorder::Show' has a wrong offset!");

}

