#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Textures

#include "Basic.hpp"

#include "S_Background_structs.hpp"


namespace SDK::Params
{

// Function UI_Textures.UI_Textures_C.ExecuteUbergraph_UI_Textures
// 0x0008 (0x0008 - 0x0000)
struct UI_Textures_C_ExecuteUbergraph_UI_Textures final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Textures_C_ExecuteUbergraph_UI_Textures) == 0x000004, "Wrong alignment on UI_Textures_C_ExecuteUbergraph_UI_Textures");
static_assert(sizeof(UI_Textures_C_ExecuteUbergraph_UI_Textures) == 0x000008, "Wrong size on UI_Textures_C_ExecuteUbergraph_UI_Textures");
static_assert(offsetof(UI_Textures_C_ExecuteUbergraph_UI_Textures, EntryPoint) == 0x000000, "Member 'UI_Textures_C_ExecuteUbergraph_UI_Textures::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_Textures_C_ExecuteUbergraph_UI_Textures, K2Node_Event_IsDesignTime) == 0x000004, "Member 'UI_Textures_C_ExecuteUbergraph_UI_Textures::K2Node_Event_IsDesignTime' has a wrong offset!");

// Function UI_Textures.UI_Textures_C.Populate Textures List
// 0x0070 (0x0070 - 0x0000)
struct UI_Textures_C_Populate_Textures_List final
{
public:
	int32                                         MaxColumns;                                        // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Column;                                            // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Row;                                               // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class FName>                           CallFunc_GetDataTableRowNames_OutRowNames;         // 0x0020(0x0010)(ReferenceParm)
	class FName                                   CallFunc_Array_Get_Item;                           // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FS_Background                          CallFunc_GetDataTableRowFromName_OutRow;           // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue;      // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4A[0x6];                                       // 0x004A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_Slot_C*                             CallFunc_Create_ReturnValue;                       // 0x0050(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUniformGridSlot*                       CallFunc_AddChildToUniformGrid_ReturnValue;        // 0x0068(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Textures_C_Populate_Textures_List) == 0x000008, "Wrong alignment on UI_Textures_C_Populate_Textures_List");
static_assert(sizeof(UI_Textures_C_Populate_Textures_List) == 0x000070, "Wrong size on UI_Textures_C_Populate_Textures_List");
static_assert(offsetof(UI_Textures_C_Populate_Textures_List, MaxColumns) == 0x000000, "Member 'UI_Textures_C_Populate_Textures_List::MaxColumns' has a wrong offset!");
static_assert(offsetof(UI_Textures_C_Populate_Textures_List, Column) == 0x000004, "Member 'UI_Textures_C_Populate_Textures_List::Column' has a wrong offset!");
static_assert(offsetof(UI_Textures_C_Populate_Textures_List, Row) == 0x000008, "Member 'UI_Textures_C_Populate_Textures_List::Row' has a wrong offset!");
static_assert(offsetof(UI_Textures_C_Populate_Textures_List, Temp_int_Variable) == 0x00000C, "Member 'UI_Textures_C_Populate_Textures_List::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(UI_Textures_C_Populate_Textures_List, Temp_int_Variable_1) == 0x000010, "Member 'UI_Textures_C_Populate_Textures_List::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Textures_C_Populate_Textures_List, Temp_int_Loop_Counter_Variable) == 0x000014, "Member 'UI_Textures_C_Populate_Textures_List::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UI_Textures_C_Populate_Textures_List, CallFunc_Add_IntInt_ReturnValue) == 0x000018, "Member 'UI_Textures_C_Populate_Textures_List::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Textures_C_Populate_Textures_List, Temp_int_Array_Index_Variable) == 0x00001C, "Member 'UI_Textures_C_Populate_Textures_List::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UI_Textures_C_Populate_Textures_List, CallFunc_GetDataTableRowNames_OutRowNames) == 0x000020, "Member 'UI_Textures_C_Populate_Textures_List::CallFunc_GetDataTableRowNames_OutRowNames' has a wrong offset!");
static_assert(offsetof(UI_Textures_C_Populate_Textures_List, CallFunc_Array_Get_Item) == 0x000030, "Member 'UI_Textures_C_Populate_Textures_List::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_Textures_C_Populate_Textures_List, CallFunc_Array_Length_ReturnValue) == 0x000038, "Member 'UI_Textures_C_Populate_Textures_List::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Textures_C_Populate_Textures_List, CallFunc_GetDataTableRowFromName_OutRow) == 0x000040, "Member 'UI_Textures_C_Populate_Textures_List::CallFunc_GetDataTableRowFromName_OutRow' has a wrong offset!");
static_assert(offsetof(UI_Textures_C_Populate_Textures_List, CallFunc_GetDataTableRowFromName_ReturnValue) == 0x000048, "Member 'UI_Textures_C_Populate_Textures_List::CallFunc_GetDataTableRowFromName_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Textures_C_Populate_Textures_List, CallFunc_Less_IntInt_ReturnValue) == 0x000049, "Member 'UI_Textures_C_Populate_Textures_List::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Textures_C_Populate_Textures_List, CallFunc_Create_ReturnValue) == 0x000050, "Member 'UI_Textures_C_Populate_Textures_List::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Textures_C_Populate_Textures_List, CallFunc_Add_IntInt_ReturnValue_1) == 0x000058, "Member 'UI_Textures_C_Populate_Textures_List::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Textures_C_Populate_Textures_List, CallFunc_Add_IntInt_ReturnValue_2) == 0x00005C, "Member 'UI_Textures_C_Populate_Textures_List::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_Textures_C_Populate_Textures_List, CallFunc_Less_IntInt_ReturnValue_1) == 0x000060, "Member 'UI_Textures_C_Populate_Textures_List::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Textures_C_Populate_Textures_List, CallFunc_AddChildToUniformGrid_ReturnValue) == 0x000068, "Member 'UI_Textures_C_Populate_Textures_List::CallFunc_AddChildToUniformGrid_ReturnValue' has a wrong offset!");

// Function UI_Textures.UI_Textures_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_Textures_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Textures_C_PreConstruct) == 0x000001, "Wrong alignment on UI_Textures_C_PreConstruct");
static_assert(sizeof(UI_Textures_C_PreConstruct) == 0x000001, "Wrong size on UI_Textures_C_PreConstruct");
static_assert(offsetof(UI_Textures_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'UI_Textures_C_PreConstruct::IsDesignTime' has a wrong offset!");

}

