#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_CategoryButtons

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"
#include "SlateCore_structs.hpp"
#include "E_ChatCategory_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_CategoryButtons.W_CategoryButtons_C
// 0x04C0 (0x0740 - 0x0280)
class UW_CategoryButtons_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0280(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       OnWait;                                            // 0x0288(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UButton*                                Button_Category;                                   // 0x0290(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Anim;                                        // 0x0298(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Icon;                                        // 0x02A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               MySizeBox;                                         // 0x02A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        MyWidgetSwitcher;                                  // 0x02B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScaleBox*                              ScaleBox_Icon;                                     // 0x02B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpacer*                                Spacer_Left;                                       // 0x02C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpacer*                                Spacer_Right;                                      // 0x02C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_Category;                                // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          PlayerCanWrite_;                                   // 0x02D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2D9[0x7];                                      // 0x02D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FButtonStyle                           Style;                                             // 0x02E0(0x03F0)(Edit, BlueprintVisible)
	E_ChatCategory                                Category;                                          // 0x06D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6D1[0x7];                                      // 0x06D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_MainChat_C*                          MainChatRef;                                       // 0x06D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FText                                   ButtonName;                                        // 0x06E0(0x0018)(Edit, BlueprintVisible)
	bool                                          IsIcon_;                                           // 0x06F8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6F9[0x7];                                      // 0x06F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             Icon;                                              // 0x0700(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FMargin                                IconPadding;                                       // 0x0708(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	double                                        LeftSpacerSize;                                    // 0x0718(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        RightSpacerSize;                                   // 0x0720(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        OverrideWidth;                                     // 0x0728(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        OverrideHeight;                                    // 0x0730(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EVerticalAlignment                            IconVerticaleAlignement;                           // 0x0738(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EHorizontalAlignment                          IconHorizontalAlignement;                          // 0x0739(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__Button_Category_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void Construct();
	void ExecuteUbergraph_W_CategoryButtons(int32 EntryPoint);
	void OnNewMessage();
	void OnSelected();
	void OnUnSelected();
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_CategoryButtons_C">();
	}
	static class UW_CategoryButtons_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_CategoryButtons_C>();
	}
};
static_assert(alignof(UW_CategoryButtons_C) == 0x000010, "Wrong alignment on UW_CategoryButtons_C");
static_assert(sizeof(UW_CategoryButtons_C) == 0x000740, "Wrong size on UW_CategoryButtons_C");
static_assert(offsetof(UW_CategoryButtons_C, UberGraphFrame) == 0x000280, "Member 'UW_CategoryButtons_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UW_CategoryButtons_C, OnWait) == 0x000288, "Member 'UW_CategoryButtons_C::OnWait' has a wrong offset!");
static_assert(offsetof(UW_CategoryButtons_C, Button_Category) == 0x000290, "Member 'UW_CategoryButtons_C::Button_Category' has a wrong offset!");
static_assert(offsetof(UW_CategoryButtons_C, Image_Anim) == 0x000298, "Member 'UW_CategoryButtons_C::Image_Anim' has a wrong offset!");
static_assert(offsetof(UW_CategoryButtons_C, Image_Icon) == 0x0002A0, "Member 'UW_CategoryButtons_C::Image_Icon' has a wrong offset!");
static_assert(offsetof(UW_CategoryButtons_C, MySizeBox) == 0x0002A8, "Member 'UW_CategoryButtons_C::MySizeBox' has a wrong offset!");
static_assert(offsetof(UW_CategoryButtons_C, MyWidgetSwitcher) == 0x0002B0, "Member 'UW_CategoryButtons_C::MyWidgetSwitcher' has a wrong offset!");
static_assert(offsetof(UW_CategoryButtons_C, ScaleBox_Icon) == 0x0002B8, "Member 'UW_CategoryButtons_C::ScaleBox_Icon' has a wrong offset!");
static_assert(offsetof(UW_CategoryButtons_C, Spacer_Left) == 0x0002C0, "Member 'UW_CategoryButtons_C::Spacer_Left' has a wrong offset!");
static_assert(offsetof(UW_CategoryButtons_C, Spacer_Right) == 0x0002C8, "Member 'UW_CategoryButtons_C::Spacer_Right' has a wrong offset!");
static_assert(offsetof(UW_CategoryButtons_C, TextBlock_Category) == 0x0002D0, "Member 'UW_CategoryButtons_C::TextBlock_Category' has a wrong offset!");
static_assert(offsetof(UW_CategoryButtons_C, PlayerCanWrite_) == 0x0002D8, "Member 'UW_CategoryButtons_C::PlayerCanWrite_' has a wrong offset!");
static_assert(offsetof(UW_CategoryButtons_C, Style) == 0x0002E0, "Member 'UW_CategoryButtons_C::Style' has a wrong offset!");
static_assert(offsetof(UW_CategoryButtons_C, Category) == 0x0006D0, "Member 'UW_CategoryButtons_C::Category' has a wrong offset!");
static_assert(offsetof(UW_CategoryButtons_C, MainChatRef) == 0x0006D8, "Member 'UW_CategoryButtons_C::MainChatRef' has a wrong offset!");
static_assert(offsetof(UW_CategoryButtons_C, ButtonName) == 0x0006E0, "Member 'UW_CategoryButtons_C::ButtonName' has a wrong offset!");
static_assert(offsetof(UW_CategoryButtons_C, IsIcon_) == 0x0006F8, "Member 'UW_CategoryButtons_C::IsIcon_' has a wrong offset!");
static_assert(offsetof(UW_CategoryButtons_C, Icon) == 0x000700, "Member 'UW_CategoryButtons_C::Icon' has a wrong offset!");
static_assert(offsetof(UW_CategoryButtons_C, IconPadding) == 0x000708, "Member 'UW_CategoryButtons_C::IconPadding' has a wrong offset!");
static_assert(offsetof(UW_CategoryButtons_C, LeftSpacerSize) == 0x000718, "Member 'UW_CategoryButtons_C::LeftSpacerSize' has a wrong offset!");
static_assert(offsetof(UW_CategoryButtons_C, RightSpacerSize) == 0x000720, "Member 'UW_CategoryButtons_C::RightSpacerSize' has a wrong offset!");
static_assert(offsetof(UW_CategoryButtons_C, OverrideWidth) == 0x000728, "Member 'UW_CategoryButtons_C::OverrideWidth' has a wrong offset!");
static_assert(offsetof(UW_CategoryButtons_C, OverrideHeight) == 0x000730, "Member 'UW_CategoryButtons_C::OverrideHeight' has a wrong offset!");
static_assert(offsetof(UW_CategoryButtons_C, IconVerticaleAlignement) == 0x000738, "Member 'UW_CategoryButtons_C::IconVerticaleAlignement' has a wrong offset!");
static_assert(offsetof(UW_CategoryButtons_C, IconHorizontalAlignement) == 0x000739, "Member 'UW_CategoryButtons_C::IconHorizontalAlignement' has a wrong offset!");

}

