#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MessageChat

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function W_MessageChat.W_MessageChat_C.ExecuteUbergraph_W_MessageChat
// 0x00E8 (0x00E8 - 0x0000)
struct W_MessageChat_C_ExecuteUbergraph_W_MessageChat final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_WorldMessage_C*                      CallFunc_Create_ReturnValue;                       // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0010(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0020(0x0018)()
	bool                                          K2Node_CustomEvent_Visible_;                       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A[0x6];                                       // 0x003A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0048(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Len_ReturnValue;                          // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_IntInt_ReturnValue;              // 0x005C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x005D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_IntInt_ReturnValue_1;            // 0x005E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x005F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0060(0x0050)(HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue_1;          // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B1[0x7];                                       // 0x00B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_1;                          // 0x00B8(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue_1;                     // 0x00C8(0x0018)()
	ESlateVisibility                              Temp_byte_Variable;                                // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x00E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x00E2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue_2;          // 0x00E3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x00E4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat) == 0x000008, "Wrong alignment on W_MessageChat_C_ExecuteUbergraph_W_MessageChat");
static_assert(sizeof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat) == 0x0000E8, "Wrong size on W_MessageChat_C_ExecuteUbergraph_W_MessageChat");
static_assert(offsetof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat, EntryPoint) == 0x000000, "Member 'W_MessageChat_C_ExecuteUbergraph_W_MessageChat::EntryPoint' has a wrong offset!");
static_assert(offsetof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat, Temp_bool_Variable) == 0x000004, "Member 'W_MessageChat_C_ExecuteUbergraph_W_MessageChat::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat, CallFunc_Create_ReturnValue) == 0x000008, "Member 'W_MessageChat_C_ExecuteUbergraph_W_MessageChat::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat, K2Node_MakeArray_Array) == 0x000010, "Member 'W_MessageChat_C_ExecuteUbergraph_W_MessageChat::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat, CallFunc_Format_ReturnValue) == 0x000020, "Member 'W_MessageChat_C_ExecuteUbergraph_W_MessageChat::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat, K2Node_CustomEvent_Visible_) == 0x000038, "Member 'W_MessageChat_C_ExecuteUbergraph_W_MessageChat::K2Node_CustomEvent_Visible_' has a wrong offset!");
static_assert(offsetof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat, K2Node_SwitchEnum_CmpSuccess) == 0x000039, "Member 'W_MessageChat_C_ExecuteUbergraph_W_MessageChat::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat, CallFunc_PlayAnimation_ReturnValue) == 0x000040, "Member 'W_MessageChat_C_ExecuteUbergraph_W_MessageChat::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat, CallFunc_Conv_TextToString_ReturnValue) == 0x000048, "Member 'W_MessageChat_C_ExecuteUbergraph_W_MessageChat::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat, CallFunc_Len_ReturnValue) == 0x000058, "Member 'W_MessageChat_C_ExecuteUbergraph_W_MessageChat::CallFunc_Len_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat, CallFunc_NotEqual_IntInt_ReturnValue) == 0x00005C, "Member 'W_MessageChat_C_ExecuteUbergraph_W_MessageChat::CallFunc_NotEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat, CallFunc_Greater_IntInt_ReturnValue) == 0x00005D, "Member 'W_MessageChat_C_ExecuteUbergraph_W_MessageChat::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat, CallFunc_NotEqual_IntInt_ReturnValue_1) == 0x00005E, "Member 'W_MessageChat_C_ExecuteUbergraph_W_MessageChat::CallFunc_NotEqual_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x00005F, "Member 'W_MessageChat_C_ExecuteUbergraph_W_MessageChat::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat, K2Node_MakeStruct_FormatArgumentData) == 0x000060, "Member 'W_MessageChat_C_ExecuteUbergraph_W_MessageChat::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat, CallFunc_NotEqual_ByteByte_ReturnValue_1) == 0x0000B0, "Member 'W_MessageChat_C_ExecuteUbergraph_W_MessageChat::CallFunc_NotEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat, K2Node_MakeArray_Array_1) == 0x0000B8, "Member 'W_MessageChat_C_ExecuteUbergraph_W_MessageChat::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat, CallFunc_Format_ReturnValue_1) == 0x0000C8, "Member 'W_MessageChat_C_ExecuteUbergraph_W_MessageChat::CallFunc_Format_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat, Temp_byte_Variable) == 0x0000E0, "Member 'W_MessageChat_C_ExecuteUbergraph_W_MessageChat::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat, K2Node_Event_IsDesignTime) == 0x0000E1, "Member 'W_MessageChat_C_ExecuteUbergraph_W_MessageChat::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat, Temp_byte_Variable_1) == 0x0000E2, "Member 'W_MessageChat_C_ExecuteUbergraph_W_MessageChat::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat, CallFunc_NotEqual_ByteByte_ReturnValue_2) == 0x0000E3, "Member 'W_MessageChat_C_ExecuteUbergraph_W_MessageChat::CallFunc_NotEqual_ByteByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_MessageChat_C_ExecuteUbergraph_W_MessageChat, K2Node_Select_Default) == 0x0000E4, "Member 'W_MessageChat_C_ExecuteUbergraph_W_MessageChat::K2Node_Select_Default' has a wrong offset!");

// Function W_MessageChat.W_MessageChat_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct W_MessageChat_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_MessageChat_C_PreConstruct) == 0x000001, "Wrong alignment on W_MessageChat_C_PreConstruct");
static_assert(sizeof(W_MessageChat_C_PreConstruct) == 0x000001, "Wrong size on W_MessageChat_C_PreConstruct");
static_assert(offsetof(W_MessageChat_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'W_MessageChat_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function W_MessageChat.W_MessageChat_C.RefreshTimeVisibility
// 0x0001 (0x0001 - 0x0000)
struct W_MessageChat_C_RefreshTimeVisibility final
{
public:
	bool                                          Visible_;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_MessageChat_C_RefreshTimeVisibility) == 0x000001, "Wrong alignment on W_MessageChat_C_RefreshTimeVisibility");
static_assert(sizeof(W_MessageChat_C_RefreshTimeVisibility) == 0x000001, "Wrong size on W_MessageChat_C_RefreshTimeVisibility");
static_assert(offsetof(W_MessageChat_C_RefreshTimeVisibility, Visible_) == 0x000000, "Member 'W_MessageChat_C_RefreshTimeVisibility::Visible_' has a wrong offset!");

}

