#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ComboBoxItemBase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_ComboBoxItemBase.WBP_ComboBoxItemBase_C
// 0x0068 (0x02E8 - 0x0280)
class UWBP_ComboBoxItemBase_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0280(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                ItemBorder;                                        // 0x0288(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ItemButton;                                        // 0x0290(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             ItemText;                                          // 0x0298(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FString                                 TextString;                                        // 0x02A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	int32                                         ItemIndex;                                         // 0x02B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_2B4[0x4];                                      // 0x02B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	FMulticastInlineDelegateProperty_             OnComboBoxItemClicked;                             // 0x02B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_             OnComboBoxItemHover;                               // 0x02C8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_             OnComboBoxItemUnhover;                             // 0x02D8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void BndEvt__WBP_ComboBoxItemBase_ItemButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__WBP_ComboBoxItemBase_ItemButton_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature();
	void BndEvt__WBP_ComboBoxItemBase_ItemButton_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__WBP_ComboBoxItemBase_ItemButton_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature();
	void Construct();
	void ExecuteUbergraph_WBP_ComboBoxItemBase(int32 EntryPoint);
	void OnComboBoxItemClicked__DelegateSignature(class UWBP_ComboBoxItemBase_C* ComboBoxItem);
	void OnComboBoxItemHover__DelegateSignature(class UWBP_ComboBoxItemBase_C* ComboBoxItem);
	void OnComboBoxItemUnhover__DelegateSignature(class UWBP_ComboBoxItemBase_C* ComboBoxItem);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_ComboBoxItemBase_C">();
	}
	static class UWBP_ComboBoxItemBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ComboBoxItemBase_C>();
	}
};
static_assert(alignof(UWBP_ComboBoxItemBase_C) == 0x000008, "Wrong alignment on UWBP_ComboBoxItemBase_C");
static_assert(sizeof(UWBP_ComboBoxItemBase_C) == 0x0002E8, "Wrong size on UWBP_ComboBoxItemBase_C");
static_assert(offsetof(UWBP_ComboBoxItemBase_C, UberGraphFrame) == 0x000280, "Member 'UWBP_ComboBoxItemBase_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_ComboBoxItemBase_C, ItemBorder) == 0x000288, "Member 'UWBP_ComboBoxItemBase_C::ItemBorder' has a wrong offset!");
static_assert(offsetof(UWBP_ComboBoxItemBase_C, ItemButton) == 0x000290, "Member 'UWBP_ComboBoxItemBase_C::ItemButton' has a wrong offset!");
static_assert(offsetof(UWBP_ComboBoxItemBase_C, ItemText) == 0x000298, "Member 'UWBP_ComboBoxItemBase_C::ItemText' has a wrong offset!");
static_assert(offsetof(UWBP_ComboBoxItemBase_C, TextString) == 0x0002A0, "Member 'UWBP_ComboBoxItemBase_C::TextString' has a wrong offset!");
static_assert(offsetof(UWBP_ComboBoxItemBase_C, ItemIndex) == 0x0002B0, "Member 'UWBP_ComboBoxItemBase_C::ItemIndex' has a wrong offset!");
static_assert(offsetof(UWBP_ComboBoxItemBase_C, OnComboBoxItemClicked) == 0x0002B8, "Member 'UWBP_ComboBoxItemBase_C::OnComboBoxItemClicked' has a wrong offset!");
static_assert(offsetof(UWBP_ComboBoxItemBase_C, OnComboBoxItemHover) == 0x0002C8, "Member 'UWBP_ComboBoxItemBase_C::OnComboBoxItemHover' has a wrong offset!");
static_assert(offsetof(UWBP_ComboBoxItemBase_C, OnComboBoxItemUnhover) == 0x0002D8, "Member 'UWBP_ComboBoxItemBase_C::OnComboBoxItemUnhover' has a wrong offset!");

}

