#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_EditableText

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_EditableText.WBP_EditableText_C
// 0x0030 (0x02B0 - 0x0280)
class UWBP_EditableText_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0280(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UEditableText*                          EditableText;                                      // 0x0288(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_             OnTextChanged;                                     // 0x0290(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_             OnTextCommitted;                                   // 0x02A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void BndEvt__WBP_EditableText_EditableText_K2Node_ComponentBoundEvent_0_OnEditableTextChangedEvent__DelegateSignature(const class FText& Text);
	void BndEvt__WBP_EditableText_EditableText_K2Node_ComponentBoundEvent_1_OnEditableTextCommittedEvent__DelegateSignature(const class FText& Text, ETextCommit CommitMethod);
	void ExecuteUbergraph_WBP_EditableText(int32 EntryPoint);
	void OnTextChanged__DelegateSignature(const class FText& Text);
	void OnTextCommitted__DelegateSignature(const class FText& Text, ETextCommit CommitMethod);
	void SetAppearance(const struct FFFontStyle& Font, const struct FLinearColor& Color);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_EditableText_C">();
	}
	static class UWBP_EditableText_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_EditableText_C>();
	}
};
static_assert(alignof(UWBP_EditableText_C) == 0x000008, "Wrong alignment on UWBP_EditableText_C");
static_assert(sizeof(UWBP_EditableText_C) == 0x0002B0, "Wrong size on UWBP_EditableText_C");
static_assert(offsetof(UWBP_EditableText_C, UberGraphFrame) == 0x000280, "Member 'UWBP_EditableText_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_EditableText_C, EditableText) == 0x000288, "Member 'UWBP_EditableText_C::EditableText' has a wrong offset!");
static_assert(offsetof(UWBP_EditableText_C, OnTextChanged) == 0x000290, "Member 'UWBP_EditableText_C::OnTextChanged' has a wrong offset!");
static_assert(offsetof(UWBP_EditableText_C, OnTextCommitted) == 0x0002A0, "Member 'UWBP_EditableText_C::OnTextCommitted' has a wrong offset!");

}

